apiVersion: batch/v1

kind: CronJob

metadata:

  name: reuniwatt

spec:

  schedule: "*/30 * * * *"

  jobTemplate:

    spec:

      backoffLimit: 1
      template:

        spec:

          containers:

          - name: reuniwatttest

            image: vishblip93/reuniwattsrv:latest

            imagePullPolicy: IfNotPresent

            command:

            - /bin/sh

            - -c

            - python /app/app.py

          restartPolicy: OnFailure